Traceback (most recent call last):
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data = read_dhus_logs(csvdir / 'S1-backend-AOI_inputs.csv')
plot_stats_logs(data['synchronized'], plot_max=True)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:1874[0m, in [0;36mGroupBy._agg_py_fallback[0;34m(self, how, values, ndim, alt)[0m
[1;32m   1873[0m [38;5;28;01mtry[39;00m:
[0;32m-> 1874[0m     res_values [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mgrouper[38;5;241m.[39magg_series(ser, alt, preserve_dtype[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[1;32m   1875[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/ops.py:849[0m, in [0;36mBaseGrouper.agg_series[0;34m(self, obj, func, preserve_dtype)[0m
[1;32m    847[0m     preserve_dtype [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m--> 849[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_aggregate_series_pure_python(obj, func)
[1;32m    851[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(obj) [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mand[39;00m [38;5;28mlen[39m(result) [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mand[39;00m [38;5;28misinstance[39m(obj[38;5;241m.[39mdtype, ExtensionDtype):

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/ops.py:877[0m, in [0;36mBaseGrouper._aggregate_series_pure_python[0;34m(self, obj, func)[0m
[1;32m    876[0m [38;5;28;01mfor[39;00m i, group [38;5;129;01min[39;00m [38;5;28menumerate[39m(splitter):
[0;32m--> 877[0m     res [38;5;241m=[39m func(group)
[1;32m    878[0m     res [38;5;241m=[39m extract_result(res)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:2460[0m, in [0;36mGroupBy.median.<locals>.<lambda>[0;34m(x)[0m
[1;32m   2387[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m   2388[0m [38;5;124;03mCompute median of groups, excluding missing values.[39;00m
[1;32m   2389[0m 
[0;32m   (...)[0m
[1;32m   2456[0m [38;5;124;03mFreq: MS, dtype: float64[39;00m
[1;32m   2457[0m [38;5;124;03m"""[39;00m
[1;32m   2458[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_cython_agg_general(
[1;32m   2459[0m     [38;5;124m"[39m[38;5;124mmedian[39m[38;5;124m"[39m,
[0;32m-> 2460[0m     alt[38;5;241m=[39m[38;5;28;01mlambda[39;00m x: Series(x)[38;5;241m.[39mmedian(numeric_only[38;5;241m=[39mnumeric_only),
[1;32m   2461[0m     numeric_only[38;5;241m=[39mnumeric_only,
[1;32m   2462[0m )
[1;32m   2463[0m [38;5;28;01mreturn[39;00m result[38;5;241m.[39m__finalize__([38;5;28mself[39m[38;5;241m.[39mobj, method[38;5;241m=[39m[38;5;124m"[39m[38;5;124mgroupby[39m[38;5;124m"[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/series.py:6235[0m, in [0;36mSeries.median[0;34m(self, axis, skipna, numeric_only, **kwargs)[0m
[1;32m   6227[0m [38;5;129m@doc[39m(make_doc([38;5;124m"[39m[38;5;124mmedian[39m[38;5;124m"[39m, ndim[38;5;241m=[39m[38;5;241m1[39m))
[1;32m   6228[0m [38;5;28;01mdef[39;00m [38;5;21mmedian[39m(
[1;32m   6229[0m     [38;5;28mself[39m,
[0;32m   (...)[0m
[1;32m   6233[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m   6234[0m ):
[0;32m-> 6235[0m     [38;5;28;01mreturn[39;00m NDFrame[38;5;241m.[39mmedian([38;5;28mself[39m, axis, skipna, numeric_only, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py:12003[0m, in [0;36mNDFrame.median[0;34m(self, axis, skipna, numeric_only, **kwargs)[0m
[1;32m  11996[0m [38;5;28;01mdef[39;00m [38;5;21mmedian[39m(
[1;32m  11997[0m     [38;5;28mself[39m,
[1;32m  11998[0m     axis: Axis [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;241m0[39m,
[0;32m   (...)[0m
[1;32m  12001[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[1;32m  12002[0m ) [38;5;241m-[39m[38;5;241m>[39m Series [38;5;241m|[39m [38;5;28mfloat[39m:
[0;32m> 12003[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_stat_function(
[1;32m  12004[0m         [38;5;124m"[39m[38;5;124mmedian[39m[38;5;124m"[39m, nanops[38;5;241m.[39mnanmedian, axis, skipna, numeric_only, [38;5;241m*[39m[38;5;241m*[39mkwargs
[1;32m  12005[0m     )

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py:11949[0m, in [0;36mNDFrame._stat_function[0;34m(self, name, func, axis, skipna, numeric_only, **kwargs)[0m
[1;32m  11947[0m validate_bool_kwarg(skipna, [38;5;124m"[39m[38;5;124mskipna[39m[38;5;124m"[39m, none_allowed[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m> 11949[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_reduce(
[1;32m  11950[0m     func, name[38;5;241m=[39mname, axis[38;5;241m=[39maxis, skipna[38;5;241m=[39mskipna, numeric_only[38;5;241m=[39mnumeric_only
[1;32m  11951[0m )

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/series.py:6133[0m, in [0;36mSeries._reduce[0;34m(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)[0m
[1;32m   6129[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m(
[1;32m   6130[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mSeries.[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m does not allow [39m[38;5;132;01m{[39;00mkwd_name[38;5;132;01m}[39;00m[38;5;124m=[39m[38;5;132;01m{[39;00mnumeric_only[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[1;32m   6131[0m         [38;5;124m"[39m[38;5;124mwith non-numeric dtypes.[39m[38;5;124m"[39m
[1;32m   6132[0m     )
[0;32m-> 6133[0m [38;5;28;01mreturn[39;00m op(delegate, skipna[38;5;241m=[39mskipna, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/nanops.py:147[0m, in [0;36mbottleneck_switch.__call__.<locals>.f[0;34m(values, axis, skipna, **kwds)[0m
[1;32m    146[0m [38;5;28;01melse[39;00m:
[0;32m--> 147[0m     result [38;5;241m=[39m alt(values, axis[38;5;241m=[39maxis, skipna[38;5;241m=[39mskipna, [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m    149[0m [38;5;28;01mreturn[39;00m result

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/nanops.py:783[0m, in [0;36mnanmedian[0;34m(values, axis, skipna, mask)[0m
[1;32m    782[0m     [38;5;28;01mif[39;00m inferred [38;5;129;01min[39;00m [[38;5;124m"[39m[38;5;124mstring[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmixed[39m[38;5;124m"[39m]:
[0;32m--> 783[0m         [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCannot convert [39m[38;5;132;01m{[39;00mvalues[38;5;132;01m}[39;00m[38;5;124m to numeric[39m[38;5;124m"[39m)
[1;32m    784[0m [38;5;28;01mtry[39;00m:

[0;31mTypeError[0m: Cannot convert ['GRDH' 'GRDM' 'OCN' 'RAW' 'SLC'] to numeric

The above exception was the direct cause of the following exception:

[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[17], line 1[0m
[0;32m----> 1[0m data [38;5;241m=[39m read_dhus_logs(csvdir [38;5;241m/[39m [38;5;124m'[39m[38;5;124mS1-backend-AOI_inputs.csv[39m[38;5;124m'[39m)
[1;32m      2[0m plot_stats_logs(data[[38;5;124m'[39m[38;5;124msynchronized[39m[38;5;124m'[39m], plot_max[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

Cell [0;32mIn[15], line 7[0m, in [0;36mread_dhus_logs[0;34m(file)[0m
[1;32m      5[0m d [38;5;241m=[39m data[data[[38;5;124m'[39m[38;5;124maction[39m[38;5;124m'[39m] [38;5;241m==[39m action_type][38;5;241m.[39mdrop([38;5;124m'[39m[38;5;124maction[39m[38;5;124m'[39m, axis[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      6[0m stats_1 [38;5;241m=[39m d[38;5;241m.[39mgroupby([[38;5;124m'[39m[38;5;124mday[39m[38;5;124m'[39m])[38;5;241m.[39msum()[[[38;5;124m'[39m[38;5;124msize[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnumber[39m[38;5;124m'[39m]]
[0;32m----> 7[0m stats_2 [38;5;241m=[39m d[38;5;241m.[39mgroupby([[38;5;124m'[39m[38;5;124mday[39m[38;5;124m'[39m])[38;5;241m.[39mmedian()[[38;5;124m'[39m[38;5;124mtimeliness[39m[38;5;124m'[39m]
[1;32m      8[0m stats [38;5;241m=[39m stats_1[38;5;241m.[39mjoin(stats_2)
[1;32m      9[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(stats) [38;5;241m>[39m [38;5;241m0[39m:

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:2458[0m, in [0;36mGroupBy.median[0;34m(self, numeric_only)[0m
[1;32m   2385[0m [38;5;129m@final[39m
[1;32m   2386[0m [38;5;28;01mdef[39;00m [38;5;21mmedian[39m([38;5;28mself[39m, numeric_only: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mFalse[39;00m):
[1;32m   2387[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   2388[0m [38;5;124;03m    Compute median of groups, excluding missing values.[39;00m
[1;32m   2389[0m 
[0;32m   (...)[0m
[1;32m   2456[0m [38;5;124;03m    Freq: MS, dtype: float64[39;00m
[1;32m   2457[0m [38;5;124;03m    """[39;00m
[0;32m-> 2458[0m     result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_cython_agg_general(
[1;32m   2459[0m         [38;5;124m"[39m[38;5;124mmedian[39m[38;5;124m"[39m,
[1;32m   2460[0m         alt[38;5;241m=[39m[38;5;28;01mlambda[39;00m x: Series(x)[38;5;241m.[39mmedian(numeric_only[38;5;241m=[39mnumeric_only),
[1;32m   2461[0m         numeric_only[38;5;241m=[39mnumeric_only,
[1;32m   2462[0m     )
[1;32m   2463[0m     [38;5;28;01mreturn[39;00m result[38;5;241m.[39m__finalize__([38;5;28mself[39m[38;5;241m.[39mobj, method[38;5;241m=[39m[38;5;124m"[39m[38;5;124mgroupby[39m[38;5;124m"[39m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:1929[0m, in [0;36mGroupBy._cython_agg_general[0;34m(self, how, alt, numeric_only, min_count, **kwargs)[0m
[1;32m   1926[0m     result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_agg_py_fallback(how, values, ndim[38;5;241m=[39mdata[38;5;241m.[39mndim, alt[38;5;241m=[39malt)
[1;32m   1927[0m     [38;5;28;01mreturn[39;00m result
[0;32m-> 1929[0m new_mgr [38;5;241m=[39m data[38;5;241m.[39mgrouped_reduce(array_func)
[1;32m   1930[0m res [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_wrap_agged_manager(new_mgr)
[1;32m   1931[0m out [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_wrap_aggregated_output(res)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/internals/managers.py:1428[0m, in [0;36mBlockManager.grouped_reduce[0;34m(self, func)[0m
[1;32m   1424[0m [38;5;28;01mif[39;00m blk[38;5;241m.[39mis_object:
[1;32m   1425[0m     [38;5;66;03m# split on object-dtype blocks bc some columns may raise[39;00m
[1;32m   1426[0m     [38;5;66;03m#  while others do not.[39;00m
[1;32m   1427[0m     [38;5;28;01mfor[39;00m sb [38;5;129;01min[39;00m blk[38;5;241m.[39m_split():
[0;32m-> 1428[0m         applied [38;5;241m=[39m sb[38;5;241m.[39mapply(func)
[1;32m   1429[0m         result_blocks [38;5;241m=[39m extend_blocks(applied, result_blocks)
[1;32m   1430[0m [38;5;28;01melse[39;00m:

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/internals/blocks.py:366[0m, in [0;36mBlock.apply[0;34m(self, func, **kwargs)[0m
[1;32m    360[0m [38;5;129m@final[39m
[1;32m    361[0m [38;5;28;01mdef[39;00m [38;5;21mapply[39m([38;5;28mself[39m, func, [38;5;241m*[39m[38;5;241m*[39mkwargs) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mlist[39m[Block]:
[1;32m    362[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    363[0m [38;5;124;03m    apply the function to my values; return a block if we are not[39;00m
[1;32m    364[0m [38;5;124;03m    one[39;00m
[1;32m    365[0m [38;5;124;03m    """[39;00m
[0;32m--> 366[0m     result [38;5;241m=[39m func([38;5;28mself[39m[38;5;241m.[39mvalues, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    368[0m     result [38;5;241m=[39m maybe_coerce_values(result)
[1;32m    369[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_split_op_result(result)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:1926[0m, in [0;36mGroupBy._cython_agg_general.<locals>.array_func[0;34m(values)[0m
[1;32m   1923[0m [38;5;28;01melse[39;00m:
[1;32m   1924[0m     [38;5;28;01mreturn[39;00m result
[0;32m-> 1926[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_agg_py_fallback(how, values, ndim[38;5;241m=[39mdata[38;5;241m.[39mndim, alt[38;5;241m=[39malt)
[1;32m   1927[0m [38;5;28;01mreturn[39;00m result

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/core/groupby/groupby.py:1878[0m, in [0;36mGroupBy._agg_py_fallback[0;34m(self, how, values, ndim, alt)[0m
[1;32m   1876[0m     msg [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124magg function failed [how->[39m[38;5;132;01m{[39;00mhow[38;5;132;01m}[39;00m[38;5;124m,dtype->[39m[38;5;132;01m{[39;00mser[38;5;241m.[39mdtype[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m
[1;32m   1877[0m     [38;5;66;03m# preserve the kind of exception that raised[39;00m
[0;32m-> 1878[0m     [38;5;28;01mraise[39;00m [38;5;28mtype[39m(err)(msg) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   1880[0m [38;5;28;01mif[39;00m ser[38;5;241m.[39mdtype [38;5;241m==[39m [38;5;28mobject[39m:
[1;32m   1881[0m     res_values [38;5;241m=[39m res_values[38;5;241m.[39mastype([38;5;28mobject[39m, copy[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[0;31mTypeError[0m: agg function failed [how->median,dtype->object]

